export const arr = [
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
    {
        name:'soumydeep',
        id:'kbwdekj0',
        socketId:'qkjwkjwej'
    },
]